from decimal import Decimal
from typing import Any, Protocol

from app.models.signal import PositionView


class Exchange(Protocol):
    def get_balance(self) -> Decimal: ...
    def get_position(self, symbol: str) -> PositionView | None: ...
    def get_current_price(self, symbol: str) -> Decimal: ...
    def set_leverage(self, symbol: str, leverage: int) -> None: ...
    def place_market_order(
        self,
        symbol: str,
        side: str,
        quantity: Decimal,
        client_order_id: str,
        *,
        reduce_only: bool = False,
    ) -> dict[str, Any]: ...
    def place_stop_loss(
        self, symbol: str, side: str, price: Decimal, client_order_id: str
    ) -> dict[str, Any]: ...
    def place_take_profit(
        self, symbol: str, side: str, price: Decimal, client_order_id: str
    ) -> dict[str, Any]: ...
    def close_position(self, symbol: str, client_order_id: str) -> dict[str, Any]: ...
    def cancel_open_orders(self, symbol: str) -> None: ...
